### ISSUE TITLE
entities not extracted for 56554

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#139]
@valearna can you pls check if also for this paper there was an issue with the PDF to text extraction? thx
entities not extracted:
pas-1
pbs-3
pbs-4

**Comment by valearna** [comment]
pas-1: first mention in text has a non-accepted character before the keyword and it's discardes: Yes+pas-1(mg511) - the second mention is ok

pbs-3: first mention not ok: lostLvapbs-3(mg527) - second mention not ok: (C. elegans)pbs-3(mg527)

pbs-4: first mention not ok: lostLvapbs-4(mg539) - second mention not ok: (C. elegans)pbs-4(mg539)

The issue is related to pdf to text conversion problems. Whitespaces are not recognized correctly.

**Comment by draciti** [comment]
nothing we can do about this, closing
