### ISSUE TITLE
Add release version and link to release notes

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#173]

**Comment by valearna** [comment]
@draciti @vanaukenk can you take a look at the new 'Release Notes' widget on the dev site?

**Comment by vanaukenk** [comment]
@valearna   

Looks great; just a few small suggestions for the wording:

- Implemented TFIDF in place of simple thresholds to improve precision of gene and variation recognition

- Improved datatype descriptions in ? mouse-overs

- Added FAQs and Release Notes

- Made a number of other minor improvements

For the minor improvements,  are there any we could note?  Otherwise, I wonder if we should just leave that text off of the list of Main Features.

Thanks!!

**Comment by valearna** [comment]
Thanks @vanaukenk, I updated the text in the release notes. I took out the 'minor improvements' part.

**Comment by draciti** [comment]
Looks great @valearna !
