### ISSUE TITLE
Create function to generate a pre-populated spreadsheet for each processed paper from the dashboard

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#190]
Useful for manual submissions in case authors cannot reach the website.

**Comment by valearna** [comment]
@draciti Can you take a look at a specific paper on http://textpressocentral.org:3001/ and review the manual form?

**Comment by valearna** [comment]
Also, we need to investigate if it's feasible to use xls format instead of csv.

**Comment by draciti** [comment]
Looks good. 
A couple of comments:
- First sentence: ‘Some of the results provided in this form (marked as TPC powered) have been automatically extracted by our text mining methods. Please modify the values as needed’
Remove ‘Please modify the values as needed’
And add in line 4

“Please add any entity we might have missed, and remove those that were erroneously extracted”

Without formatting (e.g. Bold), it is a bit hard to understand that ENTITIES IDENTIFIED IN THE PAPER is just a header> I wonder if authors will be confused and think they might list something in there?

For fields in which they  have to specify new entities, instead of writing 'none' put a placeholder text such as: 'List here'.
e.g.:
New Genes reported
List here

New Alleles reported
List here


In the DATATYPES header add this text after DATATYPES: 'Confirm if your paper contains any of the data types below'

**Comment by valearna** [comment]
Ready to test

**Comment by draciti** [comment]
looks good. closing
